import type { CategoryItem } from '../types.js';

export const CATEGORIES: CategoryItem[] = [
  { id: 'all', name: 'All Icons', regex: null },
  { id: 'accessibility', dataCategory: '6', name: 'Accessibility', regex: /accessib|audio|blind|deaf|ear|cane|wheelchair|subtitles|closedcaption|screenreader/i },
  { id: 'animals-nature', dataCategory: '7', name: 'Animals/Nature', regex: /cat|dog|paw|tree|plant|flower|leaf|nature|animal|bird|rabbit|horse|unicorn|snail|spider|butterfly|clover/i },
  { id: 'ar-vr', dataCategory: '8', name: 'AR/VR', regex: /augmented|virtual|vrheadset|\bvr\b|spatial|3d|headset/i },
  { id: 'arrows', dataCategory: '9', name: 'Arrows', regex: /arrow|caret|chevron|direction|moveobj|turn|uturn|redo|undo/i },
  { id: 'bookmarks-favorites', dataCategory: '10', name: 'Bookmarks/Favorites', regex: /bookmark|favorite|star|saved/i },
  { id: 'business-finance', dataCategory: '32', name: 'Business/Finance', regex: /bank|coin|dollar|euro|money|creditcard|finance|business|invoice|receipt|investment|bitcoin|crypto|atm|currenc/i },
  { id: 'charts', dataCategory: '11', name: 'Charts', regex: /chart|diagram|gantt|histogram|radar|analytics|ranking/i },
  { id: 'communication', dataCategory: '28', name: 'Communication', regex: /chat|message|msg|comment|bubble|envelope|mail|phone|call|inbox|paperplane|speech|podcast|broadcast/i },
  { id: 'design-development', dataCategory: '31', name: 'Design/Development', regex: /code|dev|brush|palette|design|layer|frame|vector|bezier|terminal|git|branch|pullrequest|eyedropper|ruler|color/i },
  { id: 'editing', dataCategory: '12', name: 'Editing', regex: /edit|pen|pencil|eraser|scissors|crop|format|text|bold|italic|underline|align|indent|heading|type|typography/i },
  { id: 'emoji', dataCategory: '13', name: 'Emoji', regex: /face|emoji|smile|laugh|grin|sad|angry|kiss|wink|ghost|poo|alien/i },
  { id: 'fashion-beauty', dataCategory: '36', name: 'Fashion/Beauty', regex: /shirt|dress|shoe|boot|hat|cap|trousers|glasses|sunglasses|lipstick|perfume|makeup|comb|tie|belt|scarf|socks|cosmetic/i },
  { id: 'files', dataCategory: '30', name: 'Files', regex: /file|document|folder|archive|zip|pdf|page|clipboard|sheet/i },
  { id: 'filtering-sorting', dataCategory: '23', name: 'Filtering/Sorting', regex: /filter|sort/i },
  { id: 'food', dataCategory: '14', name: 'Food', regex: /food|burger|pizza|apple|coffee|cup|drink|bottle|wine|champagne|cake|cookie|egg|fork|knife|spoon|bowl|restaurant|hotdrink|mug/i },
  { id: 'gaming', dataCategory: '15', name: 'Gaming', regex: /game|gamepad|joystick|dice|chess|trophy|playstation|xbox|console/i },
  { id: 'hands', dataCategory: '34', name: 'Hands', regex: /hand|finger|pointer|touch|click|palm|thumbs|wave|bicep|shaka/i },
  { id: 'healthcare-medical', dataCategory: '38', name: 'Healthcare/Medical', regex: /health|medical|hospital|doctor|medicine|pill|dna|heartpulse|syringe|mask|bandage|microscope|ambulance|potion/i },
  { id: 'holidays', dataCategory: '37', name: 'Holidays', regex: /holiday|gift|party|fireworks|candle|santa|lantern|baloon|balloon|celebrat|easter|jackolantern/i },
  { id: 'home-buildings', dataCategory: '21', name: 'Home/Buildings', regex: /house|home|building|apartment|door|garage|basement|church|temple|office|bed|chair|sofa|lamp|desk|bathtub/i },
  { id: 'loaders', dataCategory: '41', name: 'Loaders', regex: /loader|loading|spinner|progress|circlehalf|circlehalfdashed|circledashed|circlehalf|refresh|rotate/i },
  { id: 'love-romance', dataCategory: '39', name: 'Love/Romance', regex: /heart|love|romance|kiss|ring|wedding|rose/i },
  { id: 'maps-location', dataCategory: '25', name: 'Maps/Location', regex: /map|location|pin|compass|navigation|gps|route|marker|road|globe|earth/i },
  { id: 'photography-video', dataCategory: '26', name: 'Photography/Video', regex: /camera|video|photo|image|aperture|film|movie|picture|lens|clapperboard|media/i },
  { id: 'school-education', dataCategory: '19', name: 'School/Education', regex: /school|education|book|graduation|student|teacher|library|notebook|chalkboard|pencil|diploma|award|certificate/i },
  { id: 'security', dataCategory: '17', name: 'Security', regex: /lock|shield|key|password|security|protect|safe|fingerprint|incognito|ban|unlocked|padlock/i },
  { id: 'shopping', dataCategory: '18', name: 'Shopping', regex: /cart|bag|shop|basket|tag|discount|coupon|barcode|price|sale/i },
  { id: 'signs-symbols', dataCategory: '40', name: 'Signs/Symbols', regex: /sign|symbol|badge|check|xmark|cross|plus|minus|alert|warning|info|question|slash|ban|asterisk|at|hashtag|percent|infinity|sparkle/i },
  { id: 'sound-music', dataCategory: '27', name: 'Sound/Music', regex: /music|sound|audio|speaker|volume|microphone|headphones|headset|note|equalizer|playlist|radio|podcast/i },
  { id: 'sport', dataCategory: '16', name: 'Sport', regex: /sport|ball|soccer|basket|tennis|golf|baseball|rugby|volleyball|dumbbell|gym|bike|bicycle|medal|stadium/i },
  { id: 'technology-devices', dataCategory: '29', name: 'Technology/Devices', regex: /computer|laptop|mobile|phone|tablet|monitor|tv|desktop|mouse|keyboard|battery|plug|server|harddrive|microchip|bluetooth|wifi|signal|antenna|cable|router/i },
  { id: 'time', dataCategory: '20', name: 'Time', regex: /time|clock|timer|stopwatch|hourglass|calendar|alarm|schedule|history/i },
  { id: 'transportation', dataCategory: '35', name: 'Transportation', regex: /car|truck|bus|train|plane|airplane|ship|boat|bike|bicycle|scooter|taxi|helicopter|rocket|ufo|vehicle|traffic/i },
  { id: 'ui-layout', dataCategory: '33', name: 'UI/Layout', regex: /layout|grid|menu|sidebar|table|col|row|modal|dropdown|slider|toggle|button|tab|panel|stack|list|divider|view|split/i },
  { id: 'users', dataCategory: '24', name: 'Users', regex: /user|people|person|profile|group|crowd|child|account|human|avatar|team/i },
  { id: 'weather', dataCategory: '22', name: 'Weather', regex: /weather|sun|moon|cloud|rain|snow|fog|wind|lightning|storm|droplet|tornado|umbrella|temperature|humidity/i },
];

export const CATEGORY_ICON_NAMES: Record<string, string> = {
  all: 'Grid',
  accessibility: 'Accessibility',
  'animals-nature': 'Leaf',
  'ar-vr': 'VrHeadset',
  arrows: 'ArrowRight',
  'bookmarks-favorites': 'Bookmark',
  'business-finance': 'CreditCard',
  charts: 'ChartBar',
  communication: 'Msg',
  'design-development': 'Palette',
  editing: 'Pen',
  emoji: 'FaceSmile',
  'fashion-beauty': 'Shirt',
  files: 'Folder',
  'filtering-sorting': 'Filter',
  food: 'Coffee',
  gaming: 'Gamepad',
  hands: 'Hand',
  'healthcare-medical': 'HeartPulse',
  holidays: 'Gift',
  'home-buildings': 'House',
  loaders: 'Loader',
  'love-romance': 'Heart',
  'maps-location': 'Pin',
  'photography-video': 'Camera',
  'school-education': 'BookOpen',
  security: 'Shield',
  shopping: 'Bag',
  'signs-symbols': 'Sparkle',
  'sound-music': 'Music',
  sport: 'Trophy',
  'technology-devices': 'Laptop',
  time: 'Clock',
  transportation: 'Rocket',
  'ui-layout': 'Window',
  users: 'Users',
  weather: 'Sun',
};
